name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: cocogitto/cocogitto-action@v3
        with:
          check-latest-tag-only: true
          git-user: github-actions[bot]
          git-user-email: github-actions[bot]@users.noreply.github.com
