name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: git fetch --tags --force

      - run: git tag -l && git log --oneline --decorate -5

      - uses: cocogitto/cocogitto-action@v4
        with:
          command: bump
          args: --auto
          git-user: github-actions[bot]
          git-user-email: github-actions[bot]@users.noreply.github.com
